Tdl 31 make edit button black when item is being editable
MasterFrontMW/todo-app pull request #24
Opened 2022-12-15 18:39 UTC by macopul

2022-12-21 13:29 UTC, woopul requested changes

2022-12-21 13:29 UTC, woopul commented on src/ToDoItem/ToDoItem.js
>        e.preventDefault();
add return;

2022-12-21 13:29 UTC, woopul commented on src/ToDoItem/ToDoItem.js
> +    } else {
remove else - move everyting from inside out

2022-12-21 13:29 UTC, woopul commented on src/ToDoItem/ToDoItem.js
>      if (checkbox.checked) {
This if condition does not do anything

2022-12-22 07:34 UTC, macopul commented on src/ToDoItem/ToDoItem.js
>        e.preventDefault();
done

2022-12-22 07:34 UTC, macopul commented on src/ToDoItem/ToDoItem.js
> +    } else {
done

2022-12-22 07:34 UTC, macopul commented on src/ToDoItem/ToDoItem.js
>      if (checkbox.checked) {
done

2023-01-08 21:41 UTC, woopul commented
There is still a bit functionality missing - when you click on edit button it changes to black color, but when you stop editing either on clickOuttside or just by marking task as done, edit button still remains black

https://user-images.githubusercontent.com/21220135/211220485-ffabdd57-f5ea-42a5-9240-56e5425fb21c.mov

2023-01-08 23:36 UTC, macopul commented
https://user-images.githubusercontent.com/105385617/211224558-1b2093a2-4cf4-44f3-99ad-7b8983c03c89.mp4

I can not see this problem.
On the newest commit everything works fine in my opinion

2023-01-09 09:50 UTC, woopul approved these changes

2023-01-09 09:50 UTC, woopul commented
🎸 looking good

2023-01-09 09:52 UTC, merged